# serverless.yml
service: job-portal-server

provider:
  name: aws
  runtime: nodejs16.x

functions:
  app:
    handler: app.handler
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY
